#!/bin/sh
python test_cdf.py -j 0
python test_cdf.py -j 1
python test_cdf.py -j 2
python test_cdf.py -j 3
python test_cdf.py -j 4
python test_cdf.py -j 5
python test_cdf.py -j 6
python test_cdf.py -j 7
python test_cdf.py -j 8
python test_cdf.py -j 9
python test_cdf.py -j 10
python test_cdf.py -j 11
python test_cdf.py -j 12
python test_cdf.py -j 13
python test_cdf.py -j 14
python test_cdf.py -j 15
python test_cdf.py -j 16
python test_cdf.py -j 17