#!/bin/sh
./tahtiid -N 2 -fig_dir '/home/jzh/Dropbox/Research/Anomaly_Detection/Experimental_Results/N_2/'
./tahtiid -N 3 -fig_dir '/home/jzh/Dropbox/Research/Anomaly_Detection/Experimental_Results/N_3/'
./tahtiid -N 4 -fig_dir '/home/jzh/Dropbox/Research/Anomaly_Detection/Experimental_Results/N_4/'
./tahtiid -N 5 -fig_dir '/home/jzh/Dropbox/Research/Anomaly_Detection/Experimental_Results/N_5/'
./tahtiid -N 6 -fig_dir '/home/jzh/Dropbox/Research/Anomaly_Detection/Experimental_Results/N_6/'
./tahtiid -N 7 -fig_dir '/home/jzh/Dropbox/Research/Anomaly_Detection/Experimental_Results/N_7/'
./tahtiid -N 8 -fig_dir '/home/jzh/Dropbox/Research/Anomaly_Detection/Experimental_Results/N_8/'
./tahtiid -N 9 -fig_dir '/home/jzh/Dropbox/Research/Anomaly_Detection/Experimental_Results/N_9/'
./tahtiid -N 10 -fig_dir '/home/jzh/Dropbox/Research/Anomaly_Detection/Experimental_Results/N_10/'
./tahtiid -N 12 -fig_dir '/home/jzh/Dropbox/Research/Anomaly_Detection/Experimental_Results/N_12/'
./tahtiid -N 16 -fig_dir '/home/jzh/Dropbox/Research/Anomaly_Detection/Experimental_Results/N_16/'